version: '3'

services:
  spark-master:
    image: bde2020/spark-master:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
  
  spark-worker-1:
    image: bde2020/spark-worker:latest
    container_name: spark-worker-1
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    ports:
      - "8081:8081"

  spark-worker-2:
    image: bde2020/spark-worker:latest
    container_name: spark-worker-2
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    ports:
      - "8082:8081"

  spark-worker-3:
    image: bde2020/spark-worker:latest
    container_name: spark-worker-3
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    ports:
      - "8083:8081"

  # Bonus: Jupyter Notebook
  jupyter-notebook:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-pyspark-notebook
    environment:
      - "JUPYTER_ENABLE_LAB=yes"
      - "SPARK_MASTER=spark://spark-master:7077"
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
